### ISSUE TITLE
Modal réponse à une question : possibilité de revenir sur la question (au lieu d'aller à la suivante)

### ISSUE THREAD

**Issue by NicolasPhan** [AudreyPambrun/solucomandshare#3]
@DanielBaudry : Lorsque la fenêtre modale pour la réponse à la question apparaît, il est possible de cliquer hors de la modale pour la fermer. On revient alors à la question.
Le problème, c'est que lorsqu'on effectue 3 fois cette opération, après répondu à la question pour la 3e fois le quizz est fini.

**Comment by NicolasPhan** [comment]
(Oui, je suis juste là pour vous embêter)

**Comment by dionisiorocha** [comment]
http://ionicframework.com/docs/api/controller/ionicModal/

Regardez 'backdropClickToClose' et 'hardwareBackButtonClose '; Ils sont 'true' par défaut, il suffit de les changer. Merci Nico :)

**Comment by DanielBaudry** [comment]
Merci pour vos retours !
Par contre le comportement de l'appli n'est pas au top avec les 2 options positionnées.
On ne peut effectivement plus revenir à la question, par contre on ne peut plus passer à la question suivante non plus sans rafraîchir la page.

**Comment by NicolasPhan** [comment]
C'est à dire? J'arrive bien à accéder à la question suivante à chaque fois?

**Comment by dionisiorocha** [comment]
Pareil de mon coté. Il faut aussi penser que les utilisateurs seront exclusivement sur leurs apareils portables. Au moins sur mon iPhone je n'ai même pas l'option de cliquer en dehors du Modal - il couvre tout l'écran. Le principal serait la touche 'Retourner' des terminaux Android.
